CREATE TABLE IF NOT EXISTS `1_Revising_the_Select_Query_I` (
    `SELECT` VARCHAR(48) CHARACTER SET utf8
);
INSERT INTO `1_Revising_the_Select_Query_I` VALUES ('FROM CITY'),
	('WHERE COUNTRYCODE = ''USA'' AND POPULATION >100000');
