CREATE TABLE IF NOT EXISTS `3_Select_All` (
    `SELECT_NAME` VARCHAR(40) CHARACTER SET utf8
);
INSERT INTO `3_Select_All` VALUES ('FROM CITY '),
	('WHERE COUNTRYCODE = ''USA'' AND POPULATION'),
	('> 120000');
