CREATE TABLE IF NOT EXISTS `2_Revising_the_Select_Query_II` (
    `SELECT_NAME` VARCHAR(40) CHARACTER SET utf8
);
INSERT INTO `2_Revising_the_Select_Query_II` VALUES ('FROM CITY '),
	('WHERE COUNTRYCODE = ''USA'' AND POPULATION'),
	('> 120000');
